// SEO metadata per ogni indicatore economico
// Ogni entry mappa id  slug URL + metadati SEO completi

export const INDICATOR_SEO = {
  gdp_eur: {
    slug: "pil-san-marino",
    title: "PIL San Marino — Serie storica 2010–2023 | OESM",
    h1: "PIL di San Marino",
    description: "Prodotto Interno Lordo di San Marino in USD correnti. Serie storica 2010–2023, dati World Bank. Grafico interattivo e dataset scaricabile.",
    keywords: ["PIL San Marino", "GDP San Marino", "prodotto interno lordo San Marino", "economia San Marino dati"],
    intro: "Il Prodotto Interno Lordo (PIL) di San Marino misura il valore totale di beni e servizi prodotti dalla Repubblica nel corso di un anno. Con circa 1,9 miliardi di USD nel 2023, San Marino è una delle economie più piccole d'Europa ma mantiene un PIL pro capite tra i più alti al mondo, sostenuto dal settore finanziario, manifatturiero e turistico.",
    relatedSlugs: ["pil-pro-capite-san-marino", "crescita-pil-san-marino"],
  },
  gdp_per_capita: {
    slug: "pil-pro-capite-san-marino",
    title: "PIL pro capite San Marino — Dati storici | OESM",
    h1: "PIL pro capite di San Marino",
    description: "PIL pro capite di San Marino in USD. Serie storica 2010–2023. San Marino tra le economie con reddito più elevato in Europa.",
    keywords: ["PIL pro capite San Marino", "reddito pro capite San Marino", "GDP per capita San Marino"],
    intro: "Il PIL pro capite di San Marino si attesta nel 2023 a circa 56.420 USD, collocando la Repubblica tra le economie europee con il reddito medio più elevato. Il dato riflette un'economia ad alta produttività con una forza lavoro qualificata e un settore dei servizi finanziari sviluppato.",
    relatedSlugs: ["pil-san-marino", "crescita-pil-san-marino"],
  },
  gdp_growth: {
    slug: "crescita-pil-san-marino",
    title: "Crescita PIL San Marino — Tasso annuo | OESM",
    h1: "Crescita del PIL di San Marino",
    description: "Tasso di crescita annuo del PIL di San Marino. Serie storica 2010–2023. Dati World Bank in percentuale.",
    keywords: ["crescita PIL San Marino", "crescita economica San Marino", "variazione PIL San Marino"],
    intro: "Il tasso di crescita del PIL misura la variazione percentuale annua della ricchezza prodotta da San Marino. Dopo la contrazione del 2020 legata alla pandemia (–6,7%), l'economia ha registrato una forte ripresa nel biennio 2021–2022, tornando su un sentiero di crescita moderata nel 2023.",
    relatedSlugs: ["pil-san-marino", "pil-pro-capite-san-marino"],
  },
  population: {
    slug: "popolazione-san-marino",
    title: "Popolazione San Marino — Dati demografici | OESM",
    h1: "Popolazione residente di San Marino",
    description: "Popolazione residente di San Marino. Serie storica 2010–2023. Dati World Bank.",
    keywords: ["popolazione San Marino", "abitanti San Marino", "demografia San Marino"],
    intro: "San Marino conta circa 34.000 residenti, rendendola una delle nazioni più piccole al mondo per popolazione. Il dato demografico è stabile nell'ultimo decennio, con una crescita lenta ma costante sostenuta principalmente dall'immigrazione regolamentata.",
    relatedSlugs: ["forza-lavoro-san-marino", "disoccupazione-san-marino"],
  },
  unemployment: {
    slug: "disoccupazione-san-marino",
    title: "Disoccupazione San Marino — Tasso storico | OESM",
    h1: "Tasso di disoccupazione a San Marino",
    description: "Tasso di disoccupazione a San Marino. Serie storica 2010–2023. Dati World Bank in percentuale.",
    keywords: ["disoccupazione San Marino", "tasso disoccupazione San Marino", "mercato del lavoro San Marino"],
    intro: "Il tasso di disoccupazione di San Marino è strutturalmente basso rispetto alla media europea, riflettendo un mercato del lavoro caratterizzato da forte domanda di manodopera frontaliera e un tessuto produttivo diversificato. Il picco del 9,1% nel 2014 è stato superato con una progressiva riduzione negli anni successivi.",
    relatedSlugs: ["forza-lavoro-san-marino", "popolazione-san-marino"],
  },
  labor_force: {
    slug: "forza-lavoro-san-marino",
    title: "Forza lavoro San Marino — Serie storica | OESM",
    h1: "Forza lavoro totale di San Marino",
    description: "Forza lavoro totale di San Marino. Serie storica 2010–2023 con dati World Bank.",
    keywords: ["forza lavoro San Marino", "occupazione San Marino", "lavoratori San Marino"],
    intro: "La forza lavoro sammarinese include sia i residenti occupati che i lavoratori frontalieri italiani — circa 8.800 nel 2024. Questa componente transfrontaliera è strutturale nell'economia di San Marino e rappresenta una delle specificità del mercato del lavoro della Repubblica.",
    relatedSlugs: ["disoccupazione-san-marino", "popolazione-san-marino"],
  },
  inflation: {
    slug: "inflazione-san-marino",
    title: "Inflazione San Marino — Indice IPC | OESM",
    h1: "Inflazione a San Marino",
    description: "Tasso di inflazione a San Marino basato sull'Indice dei Prezzi al Consumo (IPC). Serie storica 2010–2023.",
    keywords: ["inflazione San Marino", "IPC San Marino", "prezzi al consumo San Marino", "CPI San Marino"],
    intro: "L'inflazione a San Marino è storicamente allineata a quella italiana, dato il profondo grado di integrazione economica tra i due paesi. Il picco del 2022 (8,1%) ha riflesso lo shock energetico europeo, seguito da una progressiva discesa nel 2023.",
    relatedSlugs: ["pil-san-marino", "spesa-pubblica-san-marino"],
  },
  exports_pct: {
    slug: "esportazioni-san-marino",
    title: "Esportazioni San Marino — Dati % PIL | OESM",
    h1: "Esportazioni di San Marino",
    description: "Esportazioni di San Marino in percentuale del PIL. Serie storica 2010–2023. Dati World Bank.",
    keywords: ["esportazioni San Marino", "export San Marino", "commercio estero San Marino dati"],
    intro: "Le esportazioni sammarinesi rappresentano una quota rilevante del PIL, a conferma dell'apertura commerciale della Repubblica. I principali settori esportatori sono il manifatturiero (meccanica di precisione, ceramica) e i servizi finanziari.",
    relatedSlugs: ["importazioni-san-marino", "apertura-commerciale-san-marino"],
  },
  imports_pct: {
    slug: "importazioni-san-marino",
    title: "Importazioni San Marino — Dati % PIL | OESM",
    h1: "Importazioni di San Marino",
    description: "Importazioni di San Marino in percentuale del PIL. Serie storica 2010–2023.",
    keywords: ["importazioni San Marino", "import San Marino", "commercio estero San Marino"],
    intro: "Le importazioni di San Marino sono strutturalmente elevate in rapporto al PIL, riflettendo la dipendenza della piccola economia dalla fornitura esterna di beni, energia e servizi. Il saldo commerciale è monitorato come indicatore della competitività esterna.",
    relatedSlugs: ["esportazioni-san-marino", "apertura-commerciale-san-marino"],
  },
  trade_openness: {
    slug: "apertura-commerciale-san-marino",
    title: "Apertura commerciale San Marino — % PIL | OESM",
    h1: "Apertura commerciale di San Marino",
    description: "Indice di apertura commerciale di San Marino (import + export su PIL). Serie storica 2010–2023.",
    keywords: ["apertura commerciale San Marino", "commercio estero San Marino", "trade openness San Marino"],
    intro: "L'indice di apertura commerciale — somma di import ed export in percentuale del PIL — misura il grado di integrazione di San Marino nell'economia internazionale. Valori superiori al 100% del PIL indicano un'economia fortemente orientata agli scambi con l'estero.",
    relatedSlugs: ["esportazioni-san-marino", "importazioni-san-marino"],
  },
  govt_expenditure: {
    slug: "spesa-pubblica-san-marino",
    title: "Spesa pubblica San Marino — % PIL | OESM",
    h1: "Spesa pubblica di San Marino",
    description: "Spesa pubblica di San Marino in percentuale del PIL. Serie storica 2010–2023. Dati World Bank.",
    keywords: ["spesa pubblica San Marino", "finanza pubblica San Marino", "bilancio San Marino"],
    intro: "La spesa pubblica di San Marino in percentuale del PIL riflette il ruolo dello Stato nell'economia. Il trend degli ultimi anni mostra un progressivo consolidamento fiscale, con una spesa che si è mantenuta tra il 25% e il 30% del PIL.",
    relatedSlugs: ["pil-san-marino", "inflazione-san-marino"],
  },
  tourism_arrivals: {
    slug: "turismo-san-marino-arrivi",
    title: "Turismo San Marino — Arrivi internazionali | OESM",
    h1: "Arrivi turistici a San Marino",
    description: "Arrivi di turisti internazionali a San Marino. Serie storica 2010–2023. Dati World Bank.",
    keywords: ["turismo San Marino", "arrivi turistici San Marino", "visitatori San Marino"],
    intro: "San Marino è una delle destinazioni turistiche più visitate d'Europa in rapporto alla sua superficie, con circa 2,5 milioni di visitatori all'anno nel periodo pre-pandemia. Il settore turistico è uno dei pilastri dell'economia della Repubblica insieme al manifatturiero e ai servizi finanziari.",
    relatedSlugs: ["turismo-san-marino-entrate", "pil-san-marino"],
  },
  tourism_receipts: {
    slug: "turismo-san-marino-entrate",
    title: "Entrate dal turismo San Marino — USD | OESM",
    h1: "Entrate dal turismo a San Marino",
    description: "Entrate economiche generate dal turismo internazionale a San Marino in USD. Serie storica 2010–2023.",
    keywords: ["entrate turismo San Marino", "ricavi turismo San Marino", "economia turistica San Marino"],
    intro: "Le entrate generate dal turismo rappresentano una voce significativa dell'economia sammarinese. Il dato include la spesa dei visitatori internazionali per alloggio, ristorazione, acquisti e servizi culturali durante il soggiorno nella Repubblica.",
    relatedSlugs: ["turismo-san-marino-arrivi", "pil-san-marino"],
  },
};

// Mappa inversa: slug  id indicatore
export const SLUG_TO_ID = Object.entries(INDICATOR_SEO).reduce((acc, [id, meta]) => {
  acc[meta.slug] = id;
  return acc;
}, {});
