// SEO metadata for English indicator pages
// URL pattern: /en/data/[slug]

export const INDICATOR_SEO_EN = {
  gdp_eur: {
    slug: "san-marino-gdp",
    title: "San Marino GDP — Historical Data 2010–2023 | OESM",
    h1: "San Marino GDP",
    description: "Gross Domestic Product of San Marino in EUR. Historical series 2010–2023, World Bank data. Interactive chart and downloadable dataset.",
    keywords: ["San Marino GDP", "San Marino economy", "San Marino economic data", "GDP San Marino EUR"],
    intro: "San Marino's Gross Domestic Product (GDP) measures the total value of goods and services produced by the Republic in a given year. At approximately €1.78 billion in 2023, San Marino is one of Europe's smallest economies by size, yet maintains one of the highest GDP per capita figures on the continent, sustained by its financial, manufacturing, and tourism sectors.",
    relatedSlugs: ["san-marino-gdp-per-capita", "san-marino-gdp-growth"],
  },
  gdp_per_capita: {
    slug: "san-marino-gdp-per-capita",
    title: "San Marino GDP per capita — Historical Data | OESM",
    h1: "San Marino GDP per capita",
    description: "GDP per capita of San Marino in EUR. Historical series 2010–2023. San Marino among Europe's highest income economies.",
    keywords: ["San Marino GDP per capita", "San Marino income", "GDP per capita San Marino"],
    intro: "San Marino's GDP per capita stood at approximately €52,189 in 2023, placing the Republic among the highest-income economies in Europe. The figure reflects a highly productive economy with a skilled workforce and a developed financial services sector.",
    relatedSlugs: ["san-marino-gdp", "san-marino-gdp-growth"],
  },
  gdp_growth: {
    slug: "san-marino-gdp-growth",
    title: "San Marino GDP Growth Rate — Annual Data | OESM",
    h1: "San Marino GDP Growth Rate",
    description: "Annual GDP growth rate of San Marino. Historical series 2010–2023. World Bank data in percentage.",
    keywords: ["San Marino GDP growth", "San Marino economic growth", "San Marino GDP change"],
    intro: "San Marino's GDP growth rate measures the annual percentage change in the Republic's total economic output. After a sharp contraction of –10.1% in 2020 due to the COVID-19 pandemic, the economy rebounded strongly in 2021–2022, returning to moderate growth of 2.4% in 2023.",
    relatedSlugs: ["san-marino-gdp", "san-marino-gdp-per-capita"],
  },
  population: {
    slug: "san-marino-population",
    title: "San Marino Population — Demographic Data | OESM",
    h1: "San Marino Resident Population",
    description: "Resident population of San Marino. Historical series 2010–2023. World Bank data.",
    keywords: ["San Marino population", "San Marino inhabitants", "San Marino demographics"],
    intro: "San Marino's resident population stands at approximately 33,745, making it one of the world's smallest nations by population. The demographic figure has remained stable over the past decade, with slow growth sustained mainly by regulated immigration.",
    relatedSlugs: ["san-marino-labour-force", "san-marino-unemployment"],
  },
  unemployment: {
    slug: "san-marino-unemployment",
    title: "San Marino Unemployment Rate — Historical Data | OESM",
    h1: "San Marino Unemployment Rate",
    description: "Unemployment rate in San Marino. Historical series 2010–2023. World Bank data in percentage.",
    keywords: ["San Marino unemployment", "unemployment rate San Marino", "San Marino labour market"],
    intro: "San Marino's unemployment rate is structurally low compared to the European average, reflecting a labour market characterised by strong demand for cross-border workers and a diversified productive base. The 2023 rate of 5.4% represents a return to pre-pandemic levels.",
    relatedSlugs: ["san-marino-labour-force", "san-marino-population"],
  },
  labor_force: {
    slug: "san-marino-labour-force",
    title: "San Marino Labour Force — Historical Series | OESM",
    h1: "San Marino Total Labour Force",
    description: "Total labour force in San Marino. Historical series 2010–2023, World Bank data.",
    keywords: ["San Marino labour force", "San Marino employment", "San Marino workers"],
    intro: "San Marino's labour force includes both resident workers and Italian cross-border commuters (frontalieri) — approximately 8,800 in 2024. This cross-border component is structural to San Marino's economy and represents one of the defining characteristics of its labour market.",
    relatedSlugs: ["san-marino-unemployment", "san-marino-population"],
  },
  inflation: {
    slug: "san-marino-inflation",
    title: "San Marino Inflation Rate — CPI Data | OESM",
    h1: "San Marino Inflation Rate",
    description: "Inflation rate in San Marino based on the Consumer Price Index (CPI). Historical series 2010–2023.",
    keywords: ["San Marino inflation", "CPI San Marino", "consumer prices San Marino"],
    intro: "San Marino's inflation rate is historically aligned with Italy's, given the deep degree of economic integration between the two countries. The 2022 peak of 8.7% reflected the European energy shock, followed by a gradual decline in 2023 to 5.2%.",
    relatedSlugs: ["san-marino-gdp", "san-marino-government-expenditure"],
  },
  exports_pct: {
    slug: "san-marino-exports",
    title: "San Marino Exports — % of GDP | OESM",
    h1: "San Marino Exports",
    description: "San Marino exports as a percentage of GDP. Historical series 2010–2023. World Bank data.",
    keywords: ["San Marino exports", "San Marino trade", "San Marino external trade data"],
    intro: "San Marino's exports represent a significant share of GDP, confirming the Republic's high degree of trade openness. The main export sectors are precision manufacturing, ceramics, and financial services.",
    relatedSlugs: ["san-marino-imports", "san-marino-trade-openness"],
  },
  imports_pct: {
    slug: "san-marino-imports",
    title: "San Marino Imports — % of GDP | OESM",
    h1: "San Marino Imports",
    description: "San Marino imports as a percentage of GDP. Historical series 2010–2023.",
    keywords: ["San Marino imports", "San Marino trade balance", "San Marino external trade"],
    intro: "San Marino's imports are structurally high relative to GDP, reflecting the small economy's dependence on external supply of goods, energy, and services. The trade balance is monitored as a key indicator of external competitiveness.",
    relatedSlugs: ["san-marino-exports", "san-marino-trade-openness"],
  },
  trade_openness: {
    slug: "san-marino-trade-openness",
    title: "San Marino Trade Openness — % of GDP | OESM",
    h1: "San Marino Trade Openness",
    description: "Trade openness index for San Marino (imports + exports as % of GDP). Historical series 2010–2023.",
    keywords: ["San Marino trade openness", "San Marino trade", "trade openness index San Marino"],
    intro: "The trade openness index — the sum of imports and exports as a percentage of GDP — measures San Marino's degree of integration in the international economy. Values above 300% of GDP indicate an economy heavily oriented toward external trade.",
    relatedSlugs: ["san-marino-exports", "san-marino-imports"],
  },
  govt_expenditure: {
    slug: "san-marino-government-expenditure",
    title: "San Marino Government Expenditure — % of GDP | OESM",
    h1: "San Marino Government Expenditure",
    description: "Government expenditure in San Marino as a percentage of GDP. Historical series 2010–2023.",
    keywords: ["San Marino government expenditure", "public spending San Marino", "San Marino budget"],
    intro: "San Marino's public expenditure as a share of GDP reflects the State's role in the economy. The trend over recent years shows a progressive fiscal consolidation, with spending maintained between 25% and 35% of GDP.",
    relatedSlugs: ["san-marino-gdp", "san-marino-inflation"],
  },
  tourism_arrivals: {
    slug: "san-marino-tourism-arrivals",
    title: "San Marino Tourism Arrivals — International Visitors | OESM",
    h1: "International Tourism Arrivals in San Marino",
    description: "International tourist arrivals in San Marino. Historical series 2010–2023. World Bank data.",
    keywords: ["San Marino tourism", "tourism arrivals San Marino", "visitors San Marino"],
    intro: "San Marino is one of Europe's most visited destinations relative to its surface area, attracting approximately 2.3 million international visitors in 2023. The tourism sector is a key pillar of the Republic's economy alongside manufacturing and financial services.",
    relatedSlugs: ["san-marino-tourism-receipts", "san-marino-gdp"],
  },
  tourism_receipts: {
    slug: "san-marino-tourism-receipts",
    title: "San Marino Tourism Receipts — EUR | OESM",
    h1: "Tourism Receipts in San Marino",
    description: "Economic revenue generated by international tourism in San Marino in EUR. Historical series 2010–2023.",
    keywords: ["San Marino tourism revenue", "tourism receipts San Marino", "San Marino tourist economy"],
    intro: "Tourism receipts represent a significant component of San Marino's economy. The figure includes international visitors' spending on accommodation, dining, retail, and cultural services during their stay in the Republic.",
    relatedSlugs: ["san-marino-tourism-arrivals", "san-marino-gdp"],
  },
};

// Reverse map: English slug → indicator id
export const SLUG_TO_ID_EN = Object.entries(INDICATOR_SEO_EN).reduce((acc, [id, meta]) => {
  acc[meta.slug] = id;
  return acc;
}, {});
